#!/usr/bin/env bash
declare -A NBCRED=(
  [URI]=newsboat/uri
  [USER]=newsboat/user
  [APIKEY]=newsboat/apikey
)
REPLACE() {
  for CRED in ${NBCRED[@]}; do
    if ! pass $CRED &>/dev/null; then
      pass insert $CRED
    fi
  done
  sed -e "s/$1/$2/g" -e "s/$3/$4/g" -e "s/$5/$6/g" $7 >$8
}
REPLACE URI $(pass ${NBCRED[URI]}) USER $(pass ${NBCRED[USER]}) APIKEY $(pass ${NBCRED[APIKEY]}) config.tmpl config
